# coding: utf-8

# flake8: noqa
"""
    Circuit Agent API

    Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from circuit_client.models.api_error import APIError
    from circuit_client.models.action import Action
    from circuit_client.models.action_request import ActionRequest
    from circuit_client.models.outcome import Outcome
    from circuit_client.models.reservation import Reservation
    from circuit_client.models.submit_action403_response import SubmitAction403Response

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from circuit_client.models.api_error import APIError
from circuit_client.models.action import Action
from circuit_client.models.action_request import ActionRequest
from circuit_client.models.outcome import Outcome
from circuit_client.models.reservation import Reservation
from circuit_client.models.submit_action403_response import SubmitAction403Response

""",
            name=__name__,
            doc=__doc__,
        )
    )
