# coding: utf-8

"""
    Circuit Agent API

    Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from circuit_client.models.action_request import ActionRequest
from circuit_client.models.outcome import Outcome
from circuit_client.models.reservation import Reservation
from typing import Optional, Set
from typing_extensions import Self

class Action(BaseModel):
    """
    Action
    """ # noqa: E501
    id: StrictStr
    agent_id: StrictStr
    request: ActionRequest
    digest: StrictStr
    policy_digest: StrictStr
    state: StrictStr
    reason: StrictStr
    created_at: datetime
    updated_at: datetime
    expires_at: datetime
    approved_by: Optional[StrictStr] = None
    outcome: Optional[Outcome] = None
    reservations: Optional[List[Reservation]] = None
    __properties: ClassVar[List[str]] = ["id", "agent_id", "request", "digest", "policy_digest", "state", "reason", "created_at", "updated_at", "expires_at", "approved_by", "outcome", "reservations"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'approved', 'executing', 'succeeded', 'failed', 'denied', 'rejected', 'expired', 'uncertain']):
            raise ValueError("must be one of enum values ('pending', 'approved', 'executing', 'succeeded', 'failed', 'denied', 'rejected', 'expired', 'uncertain')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Action from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of request
        if self.request:
            _dict['request'] = self.request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of outcome
        if self.outcome:
            _dict['outcome'] = self.outcome.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reservations (list)
        _items = []
        if self.reservations:
            for _item_reservations in self.reservations:
                if _item_reservations:
                    _items.append(_item_reservations.to_dict())
            _dict['reservations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Action from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "agent_id": obj.get("agent_id"),
            "request": ActionRequest.from_dict(obj["request"]) if obj.get("request") is not None else None,
            "digest": obj.get("digest"),
            "policy_digest": obj.get("policy_digest"),
            "state": obj.get("state"),
            "reason": obj.get("reason"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "expires_at": obj.get("expires_at"),
            "approved_by": obj.get("approved_by"),
            "outcome": Outcome.from_dict(obj["outcome"]) if obj.get("outcome") is not None else None,
            "reservations": [Reservation.from_dict(_item) for _item in obj["reservations"]] if obj.get("reservations") is not None else None
        })
        return _obj
