# coding: utf-8

"""
    Circuit Agent API

    Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ActionRequest(BaseModel):
    """
    ActionRequest
    """ # noqa: E501
    operation: StrictStr = Field(description="Operator-declared operation name.")
    custom_tool: Optional[StrictStr] = Field(default=None, description="Explicit configured MCP/REST/plugin target ID.")
    repository: Optional[StrictStr] = None
    workspace: Optional[StrictStr] = None
    database: Optional[StrictStr] = None
    environment: Optional[StrictStr] = None
    channel: Optional[StrictStr] = None
    account: Optional[StrictStr] = None
    args: Dict[str, Any] = Field(description="Arguments checked against the target's pinned schema.")
    __properties: ClassVar[List[str]] = ["operation", "custom_tool", "repository", "workspace", "database", "environment", "channel", "account", "args"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "custom_tool": obj.get("custom_tool"),
            "repository": obj.get("repository"),
            "workspace": obj.get("workspace"),
            "database": obj.get("database"),
            "environment": obj.get("environment"),
            "channel": obj.get("channel"),
            "account": obj.get("account"),
            "args": obj.get("args")
        })
        return _obj
