version: 2

project_name: circuit

builds:
  - id: circuit
    binary: circuit
    main: ./cmd/circuit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - circuit.yaml
      - docs/**
      - deploy/docker/**

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: circuit
    repository:
      owner: hgayan7
      name: homebrew-circuit
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://circuitproxy.com"
    binaries:
      - circuit
