/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIError,
  Action,
  ActionRequest,
  SubmitAction403Response,
} from '../models/index';
import {
    APIErrorFromJSON,
    APIErrorToJSON,
    ActionFromJSON,
    ActionToJSON,
    ActionRequestFromJSON,
    ActionRequestToJSON,
    SubmitAction403ResponseFromJSON,
    SubmitAction403ResponseToJSON,
} from '../models/index';

export interface GetActionRequest {
    id: string;
}

export interface SubmitActionRequest {
    idempotencyKey: string;
    actionRequest: ActionRequest;
}

/**
 *
 */
export class ActionsApi extends runtime.BaseAPI {

    /**
     * Read status without dispatching another action
     */
    async getActionRaw(requestParameters: GetActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Action>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("agentBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/actions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionFromJSON(jsonValue));
    }

    /**
     * Read status without dispatching another action
     */
    async getAction(requestParameters: GetActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Action> {
        const response = await this.getActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List this agent\'s actions
     */
    async listActionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Action>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("agentBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/actions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActionFromJSON));
    }

    /**
     * List this agent\'s actions
     */
    async listActions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Action>> {
        const response = await this.listActionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit an action for policy evaluation and possible execution
     */
    async submitActionRaw(requestParameters: SubmitActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Action>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling submitAction().'
            );
        }

        if (requestParameters['actionRequest'] == null) {
            throw new runtime.RequiredError(
                'actionRequest',
                'Required parameter "actionRequest" was null or undefined when calling submitAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("agentBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/actions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActionRequestToJSON(requestParameters['actionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionFromJSON(jsonValue));
    }

    /**
     * Submit an action for policy evaluation and possible execution
     */
    async submitAction(requestParameters: SubmitActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Action> {
        const response = await this.submitActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
