# coding: utf-8

# flake8: noqa

"""
    Circuit Agent API

    Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.2.0"

# Define package exports
__all__ = [
    "ActionsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIError",
    "Action",
    "ActionRequest",
    "Outcome",
    "Reservation",
    "SubmitAction403Response",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from circuit_client.api.actions_api import ActionsApi as ActionsApi

    # import ApiClient
    from circuit_client.api_response import ApiResponse as ApiResponse
    from circuit_client.api_client import ApiClient as ApiClient
    from circuit_client.configuration import Configuration as Configuration
    from circuit_client.exceptions import OpenApiException as OpenApiException
    from circuit_client.exceptions import ApiTypeError as ApiTypeError
    from circuit_client.exceptions import ApiValueError as ApiValueError
    from circuit_client.exceptions import ApiKeyError as ApiKeyError
    from circuit_client.exceptions import ApiAttributeError as ApiAttributeError
    from circuit_client.exceptions import ApiException as ApiException

    # import models into sdk package
    from circuit_client.models.api_error import APIError as APIError
    from circuit_client.models.action import Action as Action
    from circuit_client.models.action_request import ActionRequest as ActionRequest
    from circuit_client.models.outcome import Outcome as Outcome
    from circuit_client.models.reservation import Reservation as Reservation
    from circuit_client.models.submit_action403_response import SubmitAction403Response as SubmitAction403Response

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from circuit_client.api.actions_api import ActionsApi as ActionsApi

# import ApiClient
from circuit_client.api_response import ApiResponse as ApiResponse
from circuit_client.api_client import ApiClient as ApiClient
from circuit_client.configuration import Configuration as Configuration
from circuit_client.exceptions import OpenApiException as OpenApiException
from circuit_client.exceptions import ApiTypeError as ApiTypeError
from circuit_client.exceptions import ApiValueError as ApiValueError
from circuit_client.exceptions import ApiKeyError as ApiKeyError
from circuit_client.exceptions import ApiAttributeError as ApiAttributeError
from circuit_client.exceptions import ApiException as ApiException

# import models into sdk package
from circuit_client.models.api_error import APIError as APIError
from circuit_client.models.action import Action as Action
from circuit_client.models.action_request import ActionRequest as ActionRequest
from circuit_client.models.outcome import Outcome as Outcome
from circuit_client.models.reservation import Reservation as Reservation
from circuit_client.models.submit_action403_response import SubmitAction403Response as SubmitAction403Response

""",
            name=__name__,
            doc=__doc__,
        )
    )
