/*
Circuit Agent API

Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circuitclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// SubmitAction403Response - struct for SubmitAction403Response
type SubmitAction403Response struct {
	APIError *APIError
	Action   *Action
}

// APIErrorAsSubmitAction403Response is a convenience function that returns APIError wrapped in SubmitAction403Response
func APIErrorAsSubmitAction403Response(v *APIError) SubmitAction403Response {
	return SubmitAction403Response{
		APIError: v,
	}
}

// ActionAsSubmitAction403Response is a convenience function that returns Action wrapped in SubmitAction403Response
func ActionAsSubmitAction403Response(v *Action) SubmitAction403Response {
	return SubmitAction403Response{
		Action: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *SubmitAction403Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into APIError
	err = newStrictDecoder(data).Decode(&dst.APIError)
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			if err = validator.Validate(dst.APIError); err != nil {
				dst.APIError = nil
			} else {
				match++
			}
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal data into Action
	err = newStrictDecoder(data).Decode(&dst.Action)
	if err == nil {
		jsonAction, _ := json.Marshal(dst.Action)
		if string(jsonAction) == "{}" { // empty struct
			dst.Action = nil
		} else {
			if err = validator.Validate(dst.Action); err != nil {
				dst.Action = nil
			} else {
				match++
			}
		}
	} else {
		dst.Action = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.APIError = nil
		dst.Action = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SubmitAction403Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SubmitAction403Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SubmitAction403Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.Action != nil {
		return json.Marshal(&src.Action)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SubmitAction403Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.APIError != nil {
		return obj.APIError
	}

	if obj.Action != nil {
		return obj.Action
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SubmitAction403Response) GetActualInstanceValue() interface{} {
	if obj.APIError != nil {
		return *obj.APIError
	}

	if obj.Action != nil {
		return *obj.Action
	}

	// all schemas are nil
	return nil
}

type NullableSubmitAction403Response struct {
	value *SubmitAction403Response
	isSet bool
}

func (v NullableSubmitAction403Response) Get() *SubmitAction403Response {
	return v.value
}

func (v *NullableSubmitAction403Response) Set(val *SubmitAction403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitAction403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitAction403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitAction403Response(val *SubmitAction403Response) *NullableSubmitAction403Response {
	return &NullableSubmitAction403Response{value: val, isSet: true}
}

func (v NullableSubmitAction403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitAction403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
