/*
Circuit Agent API

Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circuitclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionRequest{}

// ActionRequest struct for ActionRequest
type ActionRequest struct {
	// Operator-declared operation name.
	Operation string `json:"operation"`
	// Explicit configured MCP/REST/plugin target ID.
	CustomTool  *string `json:"custom_tool,omitempty"`
	Repository  *string `json:"repository,omitempty"`
	Workspace   *string `json:"workspace,omitempty"`
	Database    *string `json:"database,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Channel     *string `json:"channel,omitempty"`
	Account     *string `json:"account,omitempty"`
	// Arguments checked against the target's pinned schema.
	Args map[string]interface{} `json:"args"`
}

type _ActionRequest ActionRequest

// NewActionRequest instantiates a new ActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionRequest(operation string, args map[string]interface{}) *ActionRequest {
	this := ActionRequest{}
	this.Operation = operation
	this.Args = args
	return &this
}

// NewActionRequestWithDefaults instantiates a new ActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionRequestWithDefaults() *ActionRequest {
	this := ActionRequest{}
	return &this
}

// GetOperation returns the Operation field value
func (o *ActionRequest) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *ActionRequest) SetOperation(v string) {
	o.Operation = v
}

// GetCustomTool returns the CustomTool field value if set, zero value otherwise.
func (o *ActionRequest) GetCustomTool() string {
	if o == nil || IsNil(o.CustomTool) {
		var ret string
		return ret
	}
	return *o.CustomTool
}

// GetCustomToolOk returns a tuple with the CustomTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetCustomToolOk() (*string, bool) {
	if o == nil || IsNil(o.CustomTool) {
		return nil, false
	}
	return o.CustomTool, true
}

// HasCustomTool returns a boolean if a field has been set.
func (o *ActionRequest) HasCustomTool() bool {
	if o != nil && !IsNil(o.CustomTool) {
		return true
	}

	return false
}

// SetCustomTool gets a reference to the given string and assigns it to the CustomTool field.
func (o *ActionRequest) SetCustomTool(v string) {
	o.CustomTool = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *ActionRequest) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *ActionRequest) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *ActionRequest) SetRepository(v string) {
	o.Repository = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *ActionRequest) GetWorkspace() string {
	if o == nil || IsNil(o.Workspace) {
		var ret string
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetWorkspaceOk() (*string, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *ActionRequest) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given string and assigns it to the Workspace field.
func (o *ActionRequest) SetWorkspace(v string) {
	o.Workspace = &v
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *ActionRequest) GetDatabase() string {
	if o == nil || IsNil(o.Database) {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetDatabaseOk() (*string, bool) {
	if o == nil || IsNil(o.Database) {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *ActionRequest) HasDatabase() bool {
	if o != nil && !IsNil(o.Database) {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *ActionRequest) SetDatabase(v string) {
	o.Database = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *ActionRequest) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *ActionRequest) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *ActionRequest) SetEnvironment(v string) {
	o.Environment = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ActionRequest) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ActionRequest) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *ActionRequest) SetChannel(v string) {
	o.Channel = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ActionRequest) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ActionRequest) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *ActionRequest) SetAccount(v string) {
	o.Account = &v
}

// GetArgs returns the Args field value
func (o *ActionRequest) GetArgs() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *ActionRequest) GetArgsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Args, true
}

// SetArgs sets field value
func (o *ActionRequest) SetArgs(v map[string]interface{}) {
	o.Args = v
}

func (o ActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation"] = o.Operation
	if !IsNil(o.CustomTool) {
		toSerialize["custom_tool"] = o.CustomTool
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.Workspace) {
		toSerialize["workspace"] = o.Workspace
	}
	if !IsNil(o.Database) {
		toSerialize["database"] = o.Database
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *ActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation",
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionRequest := _ActionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActionRequest)

	if err != nil {
		return err
	}

	*o = ActionRequest(varActionRequest)

	return err
}

type NullableActionRequest struct {
	value *ActionRequest
	isSet bool
}

func (v NullableActionRequest) Get() *ActionRequest {
	return v.value
}

func (v *NullableActionRequest) Set(val *ActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionRequest(val *ActionRequest) *NullableActionRequest {
	return &NullableActionRequest{value: val, isSet: true}
}

func (v NullableActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
