/*
Circuit Agent API

Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circuitclient

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Action type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Action{}

// Action struct for Action
type Action struct {
	Id           string        `json:"id"`
	AgentId      string        `json:"agent_id"`
	Request      ActionRequest `json:"request"`
	Digest       string        `json:"digest"`
	PolicyDigest string        `json:"policy_digest"`
	State        string        `json:"state"`
	Reason       string        `json:"reason"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	ExpiresAt    time.Time     `json:"expires_at"`
	ApprovedBy   *string       `json:"approved_by,omitempty"`
	Outcome      *Outcome      `json:"outcome,omitempty"`
	Reservations []Reservation `json:"reservations,omitempty"`
}

type _Action Action

// NewAction instantiates a new Action object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAction(id string, agentId string, request ActionRequest, digest string, policyDigest string, state string, reason string, createdAt time.Time, updatedAt time.Time, expiresAt time.Time) *Action {
	this := Action{}
	this.Id = id
	this.AgentId = agentId
	this.Request = request
	this.Digest = digest
	this.PolicyDigest = policyDigest
	this.State = state
	this.Reason = reason
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewActionWithDefaults instantiates a new Action object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionWithDefaults() *Action {
	this := Action{}
	return &this
}

// GetId returns the Id field value
func (o *Action) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Action) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Action) SetId(v string) {
	o.Id = v
}

// GetAgentId returns the AgentId field value
func (o *Action) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *Action) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *Action) SetAgentId(v string) {
	o.AgentId = v
}

// GetRequest returns the Request field value
func (o *Action) GetRequest() ActionRequest {
	if o == nil {
		var ret ActionRequest
		return ret
	}

	return o.Request
}

// GetRequestOk returns a tuple with the Request field value
// and a boolean to check if the value has been set.
func (o *Action) GetRequestOk() (*ActionRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Request, true
}

// SetRequest sets field value
func (o *Action) SetRequest(v ActionRequest) {
	o.Request = v
}

// GetDigest returns the Digest field value
func (o *Action) GetDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Digest
}

// GetDigestOk returns a tuple with the Digest field value
// and a boolean to check if the value has been set.
func (o *Action) GetDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Digest, true
}

// SetDigest sets field value
func (o *Action) SetDigest(v string) {
	o.Digest = v
}

// GetPolicyDigest returns the PolicyDigest field value
func (o *Action) GetPolicyDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyDigest
}

// GetPolicyDigestOk returns a tuple with the PolicyDigest field value
// and a boolean to check if the value has been set.
func (o *Action) GetPolicyDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyDigest, true
}

// SetPolicyDigest sets field value
func (o *Action) SetPolicyDigest(v string) {
	o.PolicyDigest = v
}

// GetState returns the State field value
func (o *Action) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Action) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Action) SetState(v string) {
	o.State = v
}

// GetReason returns the Reason field value
func (o *Action) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *Action) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *Action) SetReason(v string) {
	o.Reason = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Action) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Action) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Action) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Action) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Action) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Action) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *Action) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *Action) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *Action) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetApprovedBy returns the ApprovedBy field value if set, zero value otherwise.
func (o *Action) GetApprovedBy() string {
	if o == nil || IsNil(o.ApprovedBy) {
		var ret string
		return ret
	}
	return *o.ApprovedBy
}

// GetApprovedByOk returns a tuple with the ApprovedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Action) GetApprovedByOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovedBy) {
		return nil, false
	}
	return o.ApprovedBy, true
}

// HasApprovedBy returns a boolean if a field has been set.
func (o *Action) HasApprovedBy() bool {
	if o != nil && !IsNil(o.ApprovedBy) {
		return true
	}

	return false
}

// SetApprovedBy gets a reference to the given string and assigns it to the ApprovedBy field.
func (o *Action) SetApprovedBy(v string) {
	o.ApprovedBy = &v
}

// GetOutcome returns the Outcome field value if set, zero value otherwise.
func (o *Action) GetOutcome() Outcome {
	if o == nil || IsNil(o.Outcome) {
		var ret Outcome
		return ret
	}
	return *o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Action) GetOutcomeOk() (*Outcome, bool) {
	if o == nil || IsNil(o.Outcome) {
		return nil, false
	}
	return o.Outcome, true
}

// HasOutcome returns a boolean if a field has been set.
func (o *Action) HasOutcome() bool {
	if o != nil && !IsNil(o.Outcome) {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given Outcome and assigns it to the Outcome field.
func (o *Action) SetOutcome(v Outcome) {
	o.Outcome = &v
}

// GetReservations returns the Reservations field value if set, zero value otherwise.
func (o *Action) GetReservations() []Reservation {
	if o == nil || IsNil(o.Reservations) {
		var ret []Reservation
		return ret
	}
	return o.Reservations
}

// GetReservationsOk returns a tuple with the Reservations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Action) GetReservationsOk() ([]Reservation, bool) {
	if o == nil || IsNil(o.Reservations) {
		return nil, false
	}
	return o.Reservations, true
}

// HasReservations returns a boolean if a field has been set.
func (o *Action) HasReservations() bool {
	if o != nil && !IsNil(o.Reservations) {
		return true
	}

	return false
}

// SetReservations gets a reference to the given []Reservation and assigns it to the Reservations field.
func (o *Action) SetReservations(v []Reservation) {
	o.Reservations = v
}

func (o Action) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Action) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["agent_id"] = o.AgentId
	toSerialize["request"] = o.Request
	toSerialize["digest"] = o.Digest
	toSerialize["policy_digest"] = o.PolicyDigest
	toSerialize["state"] = o.State
	toSerialize["reason"] = o.Reason
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.ApprovedBy) {
		toSerialize["approved_by"] = o.ApprovedBy
	}
	if !IsNil(o.Outcome) {
		toSerialize["outcome"] = o.Outcome
	}
	if !IsNil(o.Reservations) {
		toSerialize["reservations"] = o.Reservations
	}
	return toSerialize, nil
}

func (o *Action) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"agent_id",
		"request",
		"digest",
		"policy_digest",
		"state",
		"reason",
		"created_at",
		"updated_at",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAction := _Action{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAction)

	if err != nil {
		return err
	}

	*o = Action(varAction)

	return err
}

type NullableAction struct {
	value *Action
	isSet bool
}

func (v NullableAction) Get() *Action {
	return v.value
}

func (v *NullableAction) Set(val *Action) {
	v.value = val
	v.isSet = true
}

func (v NullableAction) IsSet() bool {
	return v.isSet
}

func (v *NullableAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAction(val *Action) *NullableAction {
	return &NullableAction{value: val, isSet: true}
}

func (v NullableAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
