/*
Circuit Agent API

Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circuitclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Outcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Outcome{}

// Outcome struct for Outcome
type Outcome struct {
	HttpStatus int32 `json:"http_status"`
	// Provider JSON or a bounded text envelope.
	Body      interface{} `json:"body,omitempty"`
	Error     *string     `json:"error,omitempty"`
	Uncertain *bool       `json:"uncertain,omitempty"`
	Warning   *string     `json:"warning,omitempty"`
}

type _Outcome Outcome

// NewOutcome instantiates a new Outcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutcome(httpStatus int32) *Outcome {
	this := Outcome{}
	this.HttpStatus = httpStatus
	return &this
}

// NewOutcomeWithDefaults instantiates a new Outcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutcomeWithDefaults() *Outcome {
	this := Outcome{}
	return &this
}

// GetHttpStatus returns the HttpStatus field value
func (o *Outcome) GetHttpStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HttpStatus
}

// GetHttpStatusOk returns a tuple with the HttpStatus field value
// and a boolean to check if the value has been set.
func (o *Outcome) GetHttpStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HttpStatus, true
}

// SetHttpStatus sets field value
func (o *Outcome) SetHttpStatus(v int32) {
	o.HttpStatus = v
}

// GetBody returns the Body field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Outcome) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Outcome) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *Outcome) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given interface{} and assigns it to the Body field.
func (o *Outcome) SetBody(v interface{}) {
	o.Body = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *Outcome) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Outcome) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *Outcome) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *Outcome) SetError(v string) {
	o.Error = &v
}

// GetUncertain returns the Uncertain field value if set, zero value otherwise.
func (o *Outcome) GetUncertain() bool {
	if o == nil || IsNil(o.Uncertain) {
		var ret bool
		return ret
	}
	return *o.Uncertain
}

// GetUncertainOk returns a tuple with the Uncertain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Outcome) GetUncertainOk() (*bool, bool) {
	if o == nil || IsNil(o.Uncertain) {
		return nil, false
	}
	return o.Uncertain, true
}

// HasUncertain returns a boolean if a field has been set.
func (o *Outcome) HasUncertain() bool {
	if o != nil && !IsNil(o.Uncertain) {
		return true
	}

	return false
}

// SetUncertain gets a reference to the given bool and assigns it to the Uncertain field.
func (o *Outcome) SetUncertain(v bool) {
	o.Uncertain = &v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *Outcome) GetWarning() string {
	if o == nil || IsNil(o.Warning) {
		var ret string
		return ret
	}
	return *o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Outcome) GetWarningOk() (*string, bool) {
	if o == nil || IsNil(o.Warning) {
		return nil, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *Outcome) HasWarning() bool {
	if o != nil && !IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given string and assigns it to the Warning field.
func (o *Outcome) SetWarning(v string) {
	o.Warning = &v
}

func (o Outcome) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Outcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["http_status"] = o.HttpStatus
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Uncertain) {
		toSerialize["uncertain"] = o.Uncertain
	}
	if !IsNil(o.Warning) {
		toSerialize["warning"] = o.Warning
	}
	return toSerialize, nil
}

func (o *Outcome) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"http_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutcome := _Outcome{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutcome)

	if err != nil {
		return err
	}

	*o = Outcome(varOutcome)

	return err
}

type NullableOutcome struct {
	value *Outcome
	isSet bool
}

func (v NullableOutcome) Get() *Outcome {
	return v.value
}

func (v *NullableOutcome) Set(val *Outcome) {
	v.value = val
	v.isSet = true
}

func (v NullableOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutcome(val *Outcome) *NullableOutcome {
	return &NullableOutcome{value: val, isSet: true}
}

func (v NullableOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
