// Package initwizard implements the interactive `circuit init` wizard.
// It asks a few targeted questions and generates a tailored circuit.yaml.
package initwizard

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

// answers holds all wizard responses before rendering.
type answers struct {
	Mode           string // "run" | "mcp"
	Stack          string // "openai" | "anthropic" | "stripe" | "postgres" | "custom"
	HasBudget      bool
	MaxActions     int
	MaxSpend       float64
	HasAudit       bool
	RequireApproval bool
}

// Run executes the wizard, writing to outDir/circuit.yaml.
func Run(in io.Reader, out io.Writer, outDir string) error {
	scanner := bufio.NewScanner(in)

	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "⚡ Circuit Init — generate a circuit.yaml for your project")
	fmt.Fprintln(out, strings.Repeat("─", 52))

	a := &answers{}

	// ── Step 1: Integration mode ────────────────────────────
	fmt.Fprintln(out, "\nHow are you running your agent?")
	fmt.Fprintln(out, "  1) circuit run   — wrap an agent process (HTTP APIs)")
	fmt.Fprintln(out, "  2) circuit mcp   — wrap an MCP stdio server (tool calls)")
	fmt.Fprint(out, "Choice [1]: ")

	modeStr, err := readLine(scanner)
	if err != nil {
		return fmt.Errorf("aborted: %w", err)
	}
	if modeStr == "" || modeStr == "1" {
		a.Mode = "run"
	} else if modeStr == "2" {
		a.Mode = "mcp"
	} else {
		a.Mode = "run"
	}

	// ── Step 2: Stack ───────────────────────────────────────
	fmt.Fprintln(out, "\nWhat API or server are you protecting?")
	fmt.Fprintln(out, "  1) OpenAI")
	fmt.Fprintln(out, "  2) Anthropic")
	fmt.Fprintln(out, "  3) Postgres MCP")
	fmt.Fprintln(out, "  4) Stripe")
	fmt.Fprintln(out, "  5) Custom / Other")
	fmt.Fprint(out, "Choice [1]: ")

	stackStr, err := readLine(scanner)
	if err != nil {
		return fmt.Errorf("aborted: %w", err)
	}
	switch stackStr {
	case "2":
		a.Stack = "anthropic"
	case "3":
		a.Stack = "postgres"
	case "4":
		a.Stack = "stripe"
	case "5":
		a.Stack = "custom"
	default:
		a.Stack = "openai"
	}

	// ── Step 3: Budget ──────────────────────────────────────
	fmt.Fprint(out, "\nAdd spending/action budgets? [y/N]: ")
	budgetStr, err := readLine(scanner)
	if err != nil {
		return fmt.Errorf("aborted: %w", err)
	}
	if strings.ToLower(budgetStr) == "y" {
		a.HasBudget = true

		fmt.Fprint(out, "  Max actions per hour [100]: ")
		actStr, err := readLine(scanner)
		if err != nil {
			return fmt.Errorf("aborted: %w", err)
		}
		if actStr == "" {
			a.MaxActions = 100
		} else {
			n, _ := strconv.Atoi(actStr)
			if n > 0 {
				a.MaxActions = n
			} else {
				a.MaxActions = 100
			}
		}

		fmt.Fprint(out, "  Max spend per hour in USD [5.00]: ")
		spendStr, err := readLine(scanner)
		if err != nil {
			return fmt.Errorf("aborted: %w", err)
		}
		if spendStr == "" {
			a.MaxSpend = 5.00
		} else {
			f, _ := strconv.ParseFloat(spendStr, 64)
			if f > 0 {
				a.MaxSpend = f
			} else {
				a.MaxSpend = 5.00
			}
		}
	}

	// ── Step 4: Audit ───────────────────────────────────────
	fmt.Fprint(out, "\nEnable tamper-evident audit log? [y/N]: ")
	auditStr, err := readLine(scanner)
	if err != nil {
		return fmt.Errorf("aborted: %w", err)
	}
	a.HasAudit = strings.ToLower(auditStr) == "y"

	// ── Step 5: HITL ────────────────────────────────────────
	fmt.Fprint(out, "\nRequire human approval for sensitive actions? [y/N]: ")
	hitlStr, err := readLine(scanner)
	if err != nil {
		return fmt.Errorf("aborted: %w", err)
	}
	a.RequireApproval = strings.ToLower(hitlStr) == "y"

	// ── Render ──────────────────────────────────────────────
	outPath := filepath.Join(outDir, "circuit.yaml")
	if _, err := os.Stat(outPath); err == nil {
		fmt.Fprintf(out, "\n⚠️  circuit.yaml already exists in %s — skipping write.\n", outDir)
		fmt.Fprintln(out, "   Delete or rename it first if you want to regenerate.")
		return nil
	}

	content, err := render(a)
	if err != nil {
		return fmt.Errorf("render failed: %w", err)
	}

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write failed: %w", err)
	}

	printNextSteps(out, a, outPath)
	return nil
}

// readLine reads one line from the scanner, trimming whitespace.
// Returns io.EOF error when the scanner is exhausted.
func readLine(s *bufio.Scanner) (string, error) {
	if !s.Scan() {
		if err := s.Err(); err != nil {
			return "", err
		}
		return "", io.EOF
	}
	return strings.TrimSpace(s.Text()), nil
}

// ── Templates ────────────────────────────────────────────────────────────────

const policyTmpl = `# Generated by circuit init
# Docs: https://circuitproxy.com/docs
name: {{ .PolicyName }}
version: "1.0"
{{ if .HasAudit }}
audit:
  file: circuit.audit.ndjson
{{ end }}
rules:
{{ range .Rules }}
  - name: {{ .Name }}
    match: {{ .Match }}
    action: {{ .Action }}
    {{ if .RequireApproval }}require_approval: true{{ end }}
    {{ if .HasBudget }}
    budget:
      window: 1h
      max_actions: {{ .MaxActions }}
      max_spend: {{ .MaxSpend }}
    {{ end }}
{{ end }}
`

type ruleData struct {
	Name            string
	Match           string
	Action          string
	RequireApproval bool
	HasBudget       bool
	MaxActions      int
	MaxSpend        float64
}

type tmplData struct {
	PolicyName      string
	HasAudit        bool
	Rules           []ruleData
}

func render(a *answers) (string, error) {
	d := tmplData{
		PolicyName: policyName(a.Stack),
		HasAudit:   a.HasAudit,
		Rules:      rules(a),
	}

	t, err := template.New("policy").Parse(policyTmpl)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := t.Execute(&buf, d); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func policyName(stack string) string {
	names := map[string]string{
		"openai":    "openai-guard",
		"anthropic": "anthropic-guard",
		"postgres":  "postgres-guard",
		"stripe":    "stripe-guard",
		"custom":    "custom-guard",
	}
	if n, ok := names[stack]; ok {
		return n
	}
	return "circuit-policy"
}

func rules(a *answers) []ruleData {
	switch a.Stack {
	case "openai":
		return []ruleData{openAIRule(a)}
	case "anthropic":
		return []ruleData{anthropicRule(a)}
	case "postgres":
		return []ruleData{postgresRule(a)}
	case "stripe":
		return []ruleData{stripeRule(a)}
	default:
		return []ruleData{catchAllRule(a)}
	}
}

func openAIRule(a *answers) ruleData {
	return ruleData{
		Name:            "allow-openai-chat",
		Match:           `request.host == "api.openai.com"`,
		Action:          "allow",
		RequireApproval: a.RequireApproval,
		HasBudget:       a.HasBudget,
		MaxActions:      a.MaxActions,
		MaxSpend:        a.MaxSpend,
	}
}

func anthropicRule(a *answers) ruleData {
	return ruleData{
		Name:            "allow-anthropic-messages",
		Match:           `request.host == "api.anthropic.com"`,
		Action:          "allow",
		RequireApproval: a.RequireApproval,
		HasBudget:       a.HasBudget,
		MaxActions:      a.MaxActions,
		MaxSpend:        a.MaxSpend,
	}
}

func postgresRule(a *answers) ruleData {
	return ruleData{
		Name:            "block-postgres-ddl",
		Match:           `tool.name in ["query"] && tool.args.query.matches("(?i)^\\s*(DROP|TRUNCATE|ALTER)")`,
		Action:          "deny",
		RequireApproval: a.RequireApproval,
		HasBudget:       a.HasBudget,
		MaxActions:      a.MaxActions,
		MaxSpend:        a.MaxSpend,
	}
}

func stripeRule(a *answers) ruleData {
	return ruleData{
		Name:            "cap-stripe-charges",
		Match:           `request.path.startsWith("/v1/charges") && int(request.body.amount) > 10000`,
		Action:          "deny",
		RequireApproval: a.RequireApproval,
		HasBudget:       a.HasBudget,
		MaxActions:      a.MaxActions,
		MaxSpend:        a.MaxSpend,
	}
}

func catchAllRule(a *answers) ruleData {
	return ruleData{
		Name:            "allow-all",
		Match:           "true",
		Action:          "allow",
		RequireApproval: a.RequireApproval,
		HasBudget:       a.HasBudget,
		MaxActions:      a.MaxActions,
		MaxSpend:        a.MaxSpend,
	}
}

// ── Next steps ───────────────────────────────────────────────────────────────

func printNextSteps(out io.Writer, a *answers, outPath string) {
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "✅ Created", outPath)
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "Next steps:")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "  1. Review and edit circuit.yaml to tune your rules")
	fmt.Fprintln(out, "  2. Validate the policy:")
	fmt.Fprintln(out, "       circuit check")
	fmt.Fprintln(out, "")

	if a.Mode == "mcp" {
		fmt.Fprintln(out, "  3. Wrap your MCP server:")
		fmt.Fprintln(out, "       circuit mcp wrap -- npx -y @modelcontextprotocol/server-postgres")
	} else {
		fmt.Fprintln(out, "  3. Run your agent with Circuit enforcing policies:")
		fmt.Fprintln(out, "       circuit run -- python agent.py")
	}
	fmt.Fprintln(out, "")
}
