/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reservation } from './Reservation';
import {
    ReservationFromJSON,
    ReservationFromJSONTyped,
    ReservationToJSON,
    ReservationToJSONTyped,
} from './Reservation';
import type { ActionRequest } from './ActionRequest';
import {
    ActionRequestFromJSON,
    ActionRequestFromJSONTyped,
    ActionRequestToJSON,
    ActionRequestToJSONTyped,
} from './ActionRequest';
import type { Outcome } from './Outcome';
import {
    OutcomeFromJSON,
    OutcomeFromJSONTyped,
    OutcomeToJSON,
    OutcomeToJSONTyped,
} from './Outcome';

/**
 *
 * @export
 * @interface Action
 */
export interface Action {
    /**
     *
     * @type {string}
     * @memberof Action
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    agentId: string;
    /**
     *
     * @type {ActionRequest}
     * @memberof Action
     */
    request: ActionRequest;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    digest: string;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    policyDigest: string;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    state: ActionStateEnum;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    reason: string;
    /**
     *
     * @type {Date}
     * @memberof Action
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof Action
     */
    updatedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof Action
     */
    expiresAt: Date;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    approvedBy?: string;
    /**
     *
     * @type {Outcome}
     * @memberof Action
     */
    outcome?: Outcome;
    /**
     *
     * @type {Array<Reservation>}
     * @memberof Action
     */
    reservations?: Array<Reservation>;
}


/**
 * @export
 */
export const ActionStateEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Executing: 'executing',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Denied: 'denied',
    Rejected: 'rejected',
    Expired: 'expired',
    Uncertain: 'uncertain'
} as const;
export type ActionStateEnum = typeof ActionStateEnum[keyof typeof ActionStateEnum];


/**
 * Check if a given object implements the Action interface.
 */
export function instanceOfAction(value: object): value is Action {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('digest' in value) || value['digest'] === undefined) return false;
    if (!('policyDigest' in value) || value['policyDigest'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function ActionFromJSON(json: any): Action {
    return ActionFromJSONTyped(json, false);
}

export function ActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Action {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'agentId': json['agent_id'],
        'request': ActionRequestFromJSON(json['request']),
        'digest': json['digest'],
        'policyDigest': json['policy_digest'],
        'state': json['state'],
        'reason': json['reason'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'expiresAt': (new Date(json['expires_at'])),
        'approvedBy': json['approved_by'] == null ? undefined : json['approved_by'],
        'outcome': json['outcome'] == null ? undefined : OutcomeFromJSON(json['outcome']),
        'reservations': json['reservations'] == null ? undefined : ((json['reservations'] as Array<any>).map(ReservationFromJSON)),
    };
}

export function ActionToJSON(json: any): Action {
    return ActionToJSONTyped(json, false);
}

export function ActionToJSONTyped(value?: Action | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'agent_id': value['agentId'],
        'request': ActionRequestToJSON(value['request']),
        'digest': value['digest'],
        'policy_digest': value['policyDigest'],
        'state': value['state'],
        'reason': value['reason'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'expires_at': ((value['expiresAt']).toISOString()),
        'approved_by': value['approvedBy'],
        'outcome': OutcomeToJSON(value['outcome']),
        'reservations': value['reservations'] == null ? undefined : ((value['reservations'] as Array<any>).map(ReservationToJSON)),
    };
}
