/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ActionRequest
 */
export interface ActionRequest {
    /**
     * Operator-declared operation name.
     * @type {string}
     * @memberof ActionRequest
     */
    operation: string;
    /**
     * Explicit configured MCP/REST/plugin target ID.
     * @type {string}
     * @memberof ActionRequest
     */
    customTool?: string;
    /**
     *
     * @type {string}
     * @memberof ActionRequest
     */
    repository?: string;
    /**
     *
     * @type {string}
     * @memberof ActionRequest
     */
    workspace?: string;
    /**
     *
     * @type {string}
     * @memberof ActionRequest
     */
    database?: string;
    /**
     *
     * @type {string}
     * @memberof ActionRequest
     */
    environment?: string;
    /**
     *
     * @type {string}
     * @memberof ActionRequest
     */
    channel?: string;
    /**
     *
     * @type {string}
     * @memberof ActionRequest
     */
    account?: string;
    /**
     * Arguments checked against the target's pinned schema.
     * @type {{ [key: string]: any; }}
     * @memberof ActionRequest
     */
    args: { [key: string]: any; };
}

/**
 * Check if a given object implements the ActionRequest interface.
 */
export function instanceOfActionRequest(value: object): value is ActionRequest {
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('args' in value) || value['args'] === undefined) return false;
    return true;
}

export function ActionRequestFromJSON(json: any): ActionRequest {
    return ActionRequestFromJSONTyped(json, false);
}

export function ActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionRequest {
    if (json == null) {
        return json;
    }
    return {

        'operation': json['operation'],
        'customTool': json['custom_tool'] == null ? undefined : json['custom_tool'],
        'repository': json['repository'] == null ? undefined : json['repository'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
        'database': json['database'] == null ? undefined : json['database'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'channel': json['channel'] == null ? undefined : json['channel'],
        'account': json['account'] == null ? undefined : json['account'],
        'args': json['args'],
    };
}

export function ActionRequestToJSON(json: any): ActionRequest {
    return ActionRequestToJSONTyped(json, false);
}

export function ActionRequestToJSONTyped(value?: ActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'operation': value['operation'],
        'custom_tool': value['customTool'],
        'repository': value['repository'],
        'workspace': value['workspace'],
        'database': value['database'],
        'environment': value['environment'],
        'channel': value['channel'],
        'account': value['account'],
        'args': value['args'],
    };
}
