/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface APIError
 */
export interface APIError {
    /**
     *
     * @type {string}
     * @memberof APIError
     */
    error: string;
}

/**
 * Check if a given object implements the APIError interface.
 */
export function instanceOfAPIError(value: object): value is APIError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function APIErrorFromJSON(json: any): APIError {
    return APIErrorFromJSONTyped(json, false);
}

export function APIErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIError {
    if (json == null) {
        return json;
    }
    return {

        'error': json['error'],
    };
}

export function APIErrorToJSON(json: any): APIError {
    return APIErrorToJSONTyped(json, false);
}

export function APIErrorToJSONTyped(value?: APIError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': value['error'],
    };
}
