/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Outcome
 */
export interface Outcome {
    /**
     *
     * @type {number}
     * @memberof Outcome
     */
    httpStatus: number;
    /**
     * Provider JSON or a bounded text envelope.
     * @type {any}
     * @memberof Outcome
     */
    body?: any | null;
    /**
     *
     * @type {string}
     * @memberof Outcome
     */
    error?: string;
    /**
     *
     * @type {boolean}
     * @memberof Outcome
     */
    uncertain?: boolean;
    /**
     *
     * @type {string}
     * @memberof Outcome
     */
    warning?: string;
}

/**
 * Check if a given object implements the Outcome interface.
 */
export function instanceOfOutcome(value: object): value is Outcome {
    if (!('httpStatus' in value) || value['httpStatus'] === undefined) return false;
    return true;
}

export function OutcomeFromJSON(json: any): Outcome {
    return OutcomeFromJSONTyped(json, false);
}

export function OutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Outcome {
    if (json == null) {
        return json;
    }
    return {

        'httpStatus': json['http_status'],
        'body': json['body'] == null ? undefined : json['body'],
        'error': json['error'] == null ? undefined : json['error'],
        'uncertain': json['uncertain'] == null ? undefined : json['uncertain'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function OutcomeToJSON(json: any): Outcome {
    return OutcomeToJSONTyped(json, false);
}

export function OutcomeToJSONTyped(value?: Outcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'http_status': value['httpStatus'],
        'body': value['body'],
        'error': value['error'],
        'uncertain': value['uncertain'],
        'warning': value['warning'],
    };
}
