/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     *
     * @type {string}
     * @memberof Reservation
     */
    key: string;
    /**
     *
     * @type {Date}
     * @memberof Reservation
     */
    at: Date;
}

/**
 * Check if a given object implements the Reservation interface.
 */
export function instanceOfReservation(value: object): value is Reservation {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('at' in value) || value['at'] === undefined) return false;
    return true;
}

export function ReservationFromJSON(json: any): Reservation {
    return ReservationFromJSONTyped(json, false);
}

export function ReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reservation {
    if (json == null) {
        return json;
    }
    return {

        'key': json['key'],
        'at': (new Date(json['at'])),
    };
}

export function ReservationToJSON(json: any): Reservation {
    return ReservationToJSONTyped(json, false);
}

export function ReservationToJSONTyped(value?: Reservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'key': value['key'],
        'at': ((value['at']).toISOString()),
    };
}
