/* tslint:disable */
/* eslint-disable */
/**
 * Circuit Agent API
 * Submit governed actions and poll their durable status. Authenticate with an agent-only Circuit credential, never a provider or operator credential. Reuse the same Idempotency-Key and payload after transport failures. Pending is not success. Uncertain must stop automation and be reconciled by an operator; never retry it with a new key. Clients do not enforce isolation.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { APIError } from './APIError';
import {
    instanceOfAPIError,
    APIErrorFromJSON,
    APIErrorFromJSONTyped,
    APIErrorToJSON,
} from './APIError';
import type { Action } from './Action';
import {
    instanceOfAction,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
} from './Action';

/**
 * @type SubmitAction403Response
 *
 * @export
 */
export type SubmitAction403Response = APIError | Action;

export function SubmitAction403ResponseFromJSON(json: any): SubmitAction403Response {
    return SubmitAction403ResponseFromJSONTyped(json, false);
}

export function SubmitAction403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitAction403Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAPIError(json)) {
        return APIErrorFromJSONTyped(json, true);
    }
    if (instanceOfAction(json)) {
        return ActionFromJSONTyped(json, true);
    }
    return {} as any;
}

export function SubmitAction403ResponseToJSON(json: any): any {
    return SubmitAction403ResponseToJSONTyped(json, false);
}

export function SubmitAction403ResponseToJSONTyped(value?: SubmitAction403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAPIError(value)) {
        return APIErrorToJSON(value as APIError);
    }
    if (instanceOfAction(value)) {
        return ActionToJSON(value as Action);
    }
    return {};
}
