package gateway

const uiHTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Circuit · Action review</title><style>
:root{font-family:system-ui,sans-serif;color:#e9edf3;background:#10141c}body{max-width:1080px;margin:auto;padding:32px}header{display:flex;align-items:center;justify-content:space-between}h1{font-size:25px;margin-bottom:6px}p{color:#aab5c5;line-height:1.6}input,select,button{font:inherit;border:1px solid #445269;border-radius:7px;padding:10px;background:#1b2432;color:inherit}input{min-width:260px}button{cursor:pointer}button.primary{background:#f4b942;color:#171717;border-color:#f4b942}button:disabled{opacity:.5;cursor:wait}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #f4b942;outline-offset:3px}#login{margin:25px 0;display:flex;gap:10px;flex-wrap:wrap}#error{color:#ffb0a3;min-height:24px}.stats{display:flex;gap:18px;flex-wrap:wrap;margin:25px 0}.stat{background:#1b2432;padding:18px;border-radius:10px;min-width:125px}.stat strong{display:block;font-size:25px}.stat span{color:#aab5c5}article{border:1px solid #354154;border-radius:10px;margin:15px 0;padding:20px}article.pending{border-left:4px solid #f4b942}article.uncertain{border-left:4px solid #ff9c8a}.row{display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap}.badge{padding:5px 10px;background:#28344a;border-radius:5px;font-size:13px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0b0f15;padding:16px;border-radius:7px;font-size:12px;line-height:1.6}small{color:#aab5c5}.controls{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}a{color:#f4b942}summary{cursor:pointer;padding:12px 0}#empty{padding:30px;border:1px dashed #445269;border-radius:10px}footer{color:#aab5c5;font-size:13px;margin-top:35px}@media(max-width:600px){body{padding:20px}input{min-width:0;width:100%}}
[hidden]{display:none!important}
</style></head><body><header><div><h1>Circuit</h1><p>Action review</p></div><button id="logout" hidden>Sign out</button></header><form id="login"><label for="token">Operator credential<br><input id="token" type="password" autocomplete="off" required placeholder="Enter the Circuit operator token"></label><button class="primary" type="submit">Open review queue</button></form><p id="error" role="alert"></p><main id="workspace" hidden><div class="stats" id="stats"></div><div class="row"><h2>Recent actions</h2><button id="refresh">Refresh</button></div><p>Review the complete payload and commit SHA before approving. An uncertain outcome needs reconciliation; it will never be automatically retried.</p><section id="actions" aria-live="polite"></section></main><footer>Credentials stay in this tab’s memory. Showing up to 100 recent actions. Operator decisions apply to the exact stored action.</footer><script src="/ui.js" defer></script></body></html>`
const uiJS = `'use strict';
let token='',timer=null;const $=id=>document.getElementById(id);
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok&&data.error)throw Error(data.error);return data;}
function signout(){token='';clearInterval(timer);timer=null;$('actions').replaceChildren();$('stats').replaceChildren();$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('token').value='';}
$('logout').onclick=signout;$('refresh').onclick=()=>refresh();
$('login').onsubmit=async e=>{e.preventDefault();token=$('token').value;try{await refresh(true);$('token').value='';$('workspace').hidden=false;$('login').hidden=true;$('logout').hidden=false;clearInterval(timer);timer=setInterval(()=>refresh(),5000);}catch(err){token='';$('error').textContent=err.message;}};
async function refresh(throwErrors=false){try{const actions=await api('/admin/actions');$('error').textContent='';$('stats').replaceChildren();for(const [name,state] of [['Awaiting review','pending'],['Completed','succeeded'],['Need reconciliation','uncertain']]){const box=element('div',undefined,'stat');box.append(element('strong',String(actions.filter(a=>a.state===state).length)),element('span',name));$('stats').append(box);}
const focused=document.activeElement; if(focused&&focused.closest('#actions')&&focused.tagName!=='BODY')return;
$('actions').replaceChildren();if(!actions.length){$('actions').append(element('p','No actions yet.'));return;}
for(const a of actions){const card=element('article',undefined,a.state);const row=element('div',undefined,'row');row.append(element('strong',a.request.operation+' · '+(a.request.repository||a.request.workspace||a.request.database||a.request.environment||a.request.channel||a.request.account||a.request.custom_tool||'default')),element('span',a.state,'badge'));card.append(row,element('p',a.reason),element('small','Agent '+a.agent_id+' · '+new Date(a.created_at).toLocaleString()));
const details=element('details');details.append(element('summary','Review exact action and execution history'),element('pre',JSON.stringify({id:a.id,digest:a.digest,policy_digest:a.policy_digest,expires_at:a.expires_at,approved_by:a.approved_by,request:a.request,outcome:a.outcome},null,2)));
if(a.request.operation==='put_file'){details.append(element('strong','Proposed file content (UTF-8)'));try{const bytes=Uint8Array.from(atob(a.request.args.content),c=>c.charCodeAt(0));const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);details.append(element('pre',text));}catch{details.append(element('p','Binary or invalid UTF-8 content. Review the exact base64 payload before approving.'));}}
const link=element('a','Inspect repository on GitHub');link.href='https://github.com/'+a.request.repository+((a.request.operation==='merge_pr'||a.request.operation==='get_pr')?'/pull/'+a.request.args.number:'');link.target='_blank';link.rel='noopener noreferrer';if(a.request.repository)details.append(link);const eventsButton=element('button','Load history');eventsButton.type='button';eventsButton.onclick=async()=>{try{const events=await api('/admin/actions/'+a.id+'/events');eventsButton.replaceWith(element('pre',JSON.stringify(events,null,2)));}catch(err){$('error').textContent=err.message;}};details.append(element('p'),eventsButton);card.append(details);
if(a.state==='pending'){const controls=element('div',undefined,'controls');for(const decision of ['approve','reject']){const b=element('button',decision==='approve'?'Approve this exact action':'Reject',decision==='approve'?'primary':'');b.onclick=async()=>{if(decision==='approve'&&!details.open){details.open=true;$('error').textContent='Review the payload above, then click approve again.';return;}b.disabled=true;try{await api('/admin/actions/'+a.id+'/decision',{digest:a.digest,decision});b.blur();await refresh();}catch(err){$('error').textContent=err.message;b.disabled=false;}};controls.append(b);}card.append(controls);}
if(a.state==='uncertain'){const form=element('form',undefined,'controls');const select=element('select');select.setAttribute('aria-label','Reconciled outcome');for(const value of ['succeeded','failed']){const o=element('option',value==='succeeded'?'Confirmed completed':'Confirmed failed');o.value=value;select.append(o);}const note=element('input');note.required=true;note.maxLength=1000;note.placeholder='Reconciliation evidence';note.setAttribute('aria-label','Reconciliation evidence');const button=element('button','Record verified outcome');form.append(select,note,button);form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{await api('/admin/actions/'+a.id+'/reconcile',{digest:a.digest,state:select.value,note:note.value});button.blur();await refresh();}catch(err){$('error').textContent=err.message;button.disabled=false;}};card.append(form);}
$('actions').append(card);}}
catch(err){$('error').textContent=err.message;if(throwErrors)throw err;}}
`
